title: 'Luis Saavedra'
default_lang: en
author:
  name: 'Luis Saavedra Portfolio'
  email: di.luisgabriel@gmail.com

# Configuración del logo
logo: 'user/themes/portfolio-luis/images/ls-logo.svg'

taxonomies:
  - category
  - tag
metadata:
  description: 'Melbourne-based UX designer, UI design specialist, and frontend developer with a passion for user-centric design, clean code, and creating impactful digital products.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
