absolute_urls: false
timezone: Australia/Melbourne
default_locale: es
pages:
  theme: portfolio-luis
  order:
    by: default
    dir: asc
  list:
    count: 20
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
twig:
  cache: false      # Desactivado para desarrollo
  debug: false
  auto_reload: true
  autoescape: false
assets:
  css_minify: true  # Activado para producción
  js_pipeline: true # Activado para optimización
  js_minify: true   # Activado para producción
errors:
  display: true     # Mostrar errores localmente
  log: true
debugger:
  enabled: true     # Activado para ver detalles internos