# Configuración optimizada para Netlify
absolute_urls: true  # IMPORTANTE: true para producción
timezone: Australia/Melbourne
default_locale: es
force_ssl: false  # Netlify maneja SSL automáticamente
force_lowercase_urls: true

home:
  alias: '/home'

pages:
  theme: portfolio-luis
  process:
    markdown: true
    twig: true  # IMPORTANTE: true para que funcionen los templates
  markdown:
    extra: true
  redirect_trailing_slash: 1

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true      # true para producción
  debug: false     # false para producción  
  auto_reload: false  # false para producción

assets:
  css_pipeline: false
  css_minify: true
  js_pipeline: true    # true para mejor rendimiento
  js_minify: true
  enable_asset_timestamp: true  # para cache busting

errors:
  display: false   # false en producción
  log: true

debugger:
  enabled: false   # false en producción

# Configuración específica para archivos estáticos
media:
  enable_media_timestamp: true