absolute_urls: false
timezone: Australia/Melbourne
default_locale: es
pages:
  theme: portfolio-luis
  order:
    by: default
    dir: asc
  list:
    count: 20
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false
assets:
  css_minify: false    # ← Cambia esto a false
  js_pipeline: false
  js_minify: false     # ← Y esto también
errors:
  display: false
  log: true
debugger:
  enabled: false
