title: project
'@extends': default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab

          #
          # Add your custom fields here.
          # These fields will be available in the page's Content tab
          # inside the Admin Panel.
          #
          fields:
            #
            # Custom text field
            #
            header.project.customField:
              type: text
              label: Project Custom Field

            header.projectText.customField:
              type: textarea
              label: Project Text Custom Field
            #
            # Cover image
            #
            header.custom.coverImage:
              type: file
              label: Cover image
              destination: 'self@'
              multiple: false
              accept:
                - image/*