title: Project
'@extends':
  type: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: Content
          fields:
            header.title:
              type: text
              label: Project Title
              placeholder: e.g., Learnit
              validate:
                required: true

            header.content_blocks:
              type: list
              label: Content Blocks
              collapsed: true
              btnLabel: Add Block
              fields:
                .title:
                  type: text
                  label: Block Title
                  
                .content:
                  type: markdown
                  label: Content
                  
                .image:
                  type: file
                  label: Image
                  multiple: false
                  destination: '@self'
                  random_name: false
                  avoid_overwriting: true
                  accept:
                    - 'image/*'
                  filesize: 10
                  validate:
                    required: false
                    
                .text_position:
                  type: select
                  label: Text Position
                  options:
                    auto: Automatic (Alternating)
                    left: Left
                    right: Right
                  default: auto
            
            # Campos básicos del proyecto
            header.project_type:
              type: select
              label: Project Type
              options:
                'web-design': 'Web Design'
                'mobile-app': 'Mobile App'
                'ecommerce': 'Ecommerce'
                'ux-ui-design': 'UX UI Design'
              validate:
                required: true
            
            header.client:
              type: text
              label: Client
              placeholder: e.g., Tangosquared
            
            header.year:
              type: text
              label: Year
              placeholder: e.g., 2024
            
            header.project_url:
              type: url
              label: Project URL
              placeholder: https://example.com
            
            # Project details
            header.challenge:
              type: textarea
              label: Challenge
              placeholder: Describe the main challenge or problem this project solved
              help: Brief description of the project challenge
            
            header.solution:
              type: textarea
              label: Solution
              placeholder: Describe the solution or approach taken
              help: Brief description of the solution

            header.design_process:
              type: textarea
              label: design process
              placeholder: Describe the design or approach taken
              help: list the design metodologies
            
            # Imagen principal
            header.hero_image:
              type: file
              label: Hero Image
              destination: '@self'
              multiple: false
              accept:
                - image/*
              help: Main hero image for the project
            
            # Descripción del proyecto
            content:
              type: textarea
              label: Project Description
              size: large
              help: Detailed description of the project (supports Markdown)
              placeholder: |
                Write a detailed description of your project here. 
                
                You can use Markdown formatting:
                - **Bold text**
                - *Italic text*
                - [Links](https://example.com)
                - Lists and more
